// libs/ui/src/lib/static-information/privacy/privacy-policy.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'strive-privacy-policy',
  templateUrl: './privacy-policy.component.html'
})
export class PrivacyPolicy { }

<h2>Privacy Policy</h2>

<section>
  <h3>1. Our Commitment</h3>

  <p>
  Strive Journal knows that you take your privacy seriously. We do, too. We are committed to be transparent with you about our data practices and to give you control over personal data we collect about you. We don’t sell your personal data and information which is only relevant for you will be encrypted. In this Privacy Policy, we outline the reasons why we need to process your Personal Data and the manner in which it is processed. You will also read about your rights and what you can ask us to do with your personal data.
  </p>
</section>

<section>
  <h3>2. About Strive Journal</h3>

  <p>
    With Strive Journal you can set goals and journal about them by using our website (<a href="https://strivejournal.com">https://strivejournal.com</a>, “Website”) and/ore mobile app (“App”, “Strive Journal”). When you use Strive Journal we will process your personal data. This may include sensitive data about you, such as
  </p>
  <p>
    All personal data is collected, processed and secured in compliance with the General Data Protection REgulation (GDPR).
  </p>
  <p>
    If you have any additional questions about the way we process personal data, please contact us at <a href="mailto:support@strivejournal.com">support&#64;strivejournal.com</a>.
  </p>
  <p>
    This Privacy Policy was last modified on 31 October 2022.
  </p>
</section>

<section>
  <h3>3. How do we process your personal data</h3>

  <h4>3.1 Creating an account</h4>
  <p>
    You can create an account to set goals, follow others and make use of exercises. When you register for an account we ask you to provide some basic information about yourself, such as:
  </p>
  <ul>
    <li>Name</li>
    <li>Email address</li>
    <li>Password</li>
  </ul>
  <p>
    You can also use your Google account to register. If you do so, we may gain access to public profile information such as your name and email address.
  </p>
  <p>
    We process this data as it is necessary to deliver Strive Journal to you.
  </p>

  <h4>3.2 Using Strive Journal with an account</h4>
  <p>
    It is up to you how you use Strive Journal.
  </p>
  <p>
    Depending on how you use Strive Journal, we process the following data:
  </p>
  <ul>
    <li>Your personal info, such as name, email address and profile picture</li>
    <li>Your added goals and their roadmap, story and chat</li>
    <li>Whom you follow and who follows you</li>
  </ul>
  <p>
    You can delete all of your added content whenever you like. When you do, it will no longer be visible to others and be deleted from our servers.
  </p>

  <h4>3.3 Sharing your Goals</h4>
  <p>
    Strive Journal is a community. We allow you to not only keep a journal of your goals for yourself, but to share them with whomever you like.
  </p>
  <p>
    You can change the sharing settings for a specific goal at any time. For every goal, you can choose with whom you want to share your experience:
  </p>

  <ul>
    <li>Invited users only - This goal is only visible to the people that have been invited to the goal. When sharing the goal, a url with a token is created which is available for 24 hours. After 24 hours, this url is not valid anymore.</li>
    <li>Everyone - Inspire fellow achievers! Everyone can see your goal and its roadmap and story.</li>
  </ul>
  <p>
    The chat of the goal can only be read by people who have the role ‘admin’, ‘achiever’ or ‘supporter’. It cannot be read by people without an account or by people that only follow the goal. For more information about what each role can do within a goal, please refer to the <a href="https://blog.strivejournal.com/goal/team">team guide</a>.
  </p>
  <p>
    Think carefully about which data you share and who you share it with.
  </p>

  <h4>3.4 Exercises</h4>
  <p>
    Strive Journal comes with several exercises to increase the chances of success. We understand the information that can be entered can be very personal. Therefore this data is encrypted to make sure nobody except you is able to read it.
  </p>

  <h4>3.5 Mailings</h4>
  <p>
    You can subscribe to our mailings. For this, we need your name and email address. The legal basis for this is your consent. You can unsubscribe at any time by clicking the ‘unsubscribe’ button in each email.
  </p>
  <p>
    You may also receive mails which are necessary for the performance of the agreement with you, such as a password reset request or changes in our legal documentation.
  </p>

  <h4>3.6 Improving, securing and optimizing Strive Journal</h4>
  <p>
    Strive Journal is constantly in development. We need certain data to optimize your experience and to improve the services. Strive Journal makes use of the service provided by <a href="https://sentry.io/privacy/">Sentry.io</a>. Sentry collects information about software bugs you might encounter and api calls, page loads or similar requests and responses from your app.
  </p>
</section>

<section>
  <h3>4. What rights do you have?</h3>
  <p>
    You have the right to access, correction or erasure of your data. YOu can also ask us to restrict the processing or transfer your personal data and you have the right to object to the processing of your personal data.
  </p>
  <p>
    To exercise these rights, contact us at <a href="mailto:support@strivejournal.com">support&#64;strivejournal.com</a>.
  </p>
</section>

// apps/blog/src/pages/privacy-policy.tsx
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import Layout from '@theme/Layout';
import React from 'react';

export default function PrivacyPolicy(): JSX.Element {
  const {siteConfig} = useDocusaurusContext();
  return (
    <Layout
      title='Privacy Policy'>
      <main className='privacy-policy'>
        <h2>Privacy Policy</h2>
        <section>
          <h3>1. Our Commitment</h3>

          <p>
          Strive Journal knows that you take your privacy seriously. We do, too. We are committed to be transparent with you about our data practices and to give you control over personal data we collect about you. We don’t sell your personal data and information which is only relevant for you will be encrypted. In this Privacy Policy, we outline the reasons why we need to process your Personal Data and the manner in which it is processed. You will also read about your rights and what you can ask us to do with your personal data.
          </p>
        </section>

        <section>
          <h3>2. About Strive Journal</h3>

          <p>
            With Strive Journal you can set goals and journal about them by using our website (<a href="https://strivejournal.com">https://strivejournal.com</a>, “Website”) and/ore mobile app (“App”, “Strive Journal”). When you use Strive Journal we will process your personal data. This may include sensitive data about you, such as
          </p>
          <p>
            All personal data is collected, processed and secured in compliance with the General Data Protection REgulation (GDPR).
          </p>
          <p>
            If you have any additional questions about the way we process personal data, please contact us at <a href="mailto:support@strivejournal.com">support@strivejournal.com</a>.
          </p>
          <p>
            This Privacy Policy was last modified on 31 October 2022.
          </p>
        </section>

        <section>
          <h3>3. How do we process your personal data</h3>

          <h4>3.1 Creating an account</h4>
          <p>
            You can create an account to set goals, follow others and make use of exercises. When you register for an account we ask you to provide some basic information about yourself, such as:
          </p>
          <ul>
            <li>Name</li>
            <li>Email address</li>
            <li>Password</li>
          </ul>
          <p>
            You can also use your Google account to register. If you do so, we may gain access to public profile information such as your name and email address.
          </p>
          <p>
            We process this data as it is necessary to deliver Strive Journal to you.
          </p>

          <h4>3.2 Using Strive Journal with an account</h4>
          <p>
            It is up to you how you use Strive Journal.
          </p>
          <p>
            Depending on how you use Strive Journal, we process the following data:
          </p>
          <ul>
            <li>Your personal info, such as name, email address and profile picture</li>
            <li>Your added goals and their roadmap, story and chat</li>
            <li>Whom you follow and who follows you</li>
          </ul>
          <p>
            You can delete all of your added content whenever you like. When you do, it will no longer be visible to others and be deleted from our servers.
          </p>

          <h4>3.3 Sharing your Goals</h4>
          <p>
            Strive Journal is a community. We allow you to not only keep a journal of your goals for yourself, but to share them with whomever you like.
          </p>
          <p>
            You can change the sharing settings for a specific goal at any time. For every goal, you can choose with whom you want to share your experience:
          </p>

          <ul>
            <li>Invited users only - This goal is only visible to the people that have been invited to the goal. When sharing the goal, a url with a token is created which is available for 24 hours. After 24 hours, this url is not valid anymore.</li>
            <li>Everyone - Inspire fellow achievers! Everyone can see your goal and its roadmap and story.</li>
          </ul>
          <p>
            The chat of the goal can only be read by people who have the role ‘admin’, ‘achiever’ or ‘supporter’. It cannot be read by people without an account or by people that only follow the goal. For more information about what each role can do within a goal, please refer to the <a href="https://blog.strivejournal.com/goal/team">team guide</a>.
          </p>
          <p>
            Think carefully about which data you share and who you share it with.
          </p>

          <h4>3.4 Exercises</h4>
          <p>
            Strive Journal comes with several exercises to increase the chances of success. We understand the information that can be entered can be very personal. Therefore this data is encrypted to make sure nobody except you is able to read it.
          </p>

          <h4>3.5 Mailings</h4>
          <p>
            You can subscribe to our mailings. For this, we need your name and email address. The legal basis for this is your consent. You can unsubscribe at any time by clicking the ‘unsubscribe’ button in each email.
          </p>
          <p>
            You may also receive mails which are necessary for the performance of the agreement with you, such as a password reset request or changes in our legal documentation.
          </p>

          <h4>3.6 Improving, securing and optimizing Strive Journal</h4>
          <p>
            Strive Journal is constantly in development. We need certain data to optimize your experience and to improve the services. Strive Journal makes use of the service provided by <a href="https://sentry.io/privacy/">Sentry.io</a>. Sentry collects information about software bugs you might encounter and api calls, page loads or similar requests and responses from your app.
          </p>
        </section>

        <section>
          <h3>4. What rights do you have?</h3>
          <p>
            You have the right to access, correction or erasure of your data. YOu can also ask us to restrict the processing or transfer your personal data and you have the right to object to the processing of your personal data.
          </p>
          <p>
            To exercise these rights, contact us at <a href="mailto:support@strivejournal.com">support@strivejournal.com</a>.
          </p>
        </section>
      </main>
    </Layout>
  );
}
